version: "3.8"

services:
  persistencia:
    image: mysql:8.0
    container_name: autogestion-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: autogestiondb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - datosdb:/var/lib/mysql
    networks:
      - red_interna
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10


  backend:
    build: .
    container_name: autogestion-backend
    depends_on:
      persistencia:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://persistencia:3306/autogestiondb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    networks:
      - red_interna

volumes:
  datosdb:

networks:
  red_interna:
    driver: bridge
